### ISSUE TITLE
Document slide-toggle

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/fh-components#36]
Smoother version of:

```css
.slide-open-enter,
.slide-open-leave-to {
    max-height: 0;
}
.slide-open-enter-to,
.slide-open-leave {
    max-height: 100vh;
}
.slide-open-enter-active,
.slide-open-leave-active {
    transition: max-height 1s;
    overflow: hidden;
}

```
